"""Autogenerated. MAVLink supported autopilot types."""

from enum import IntEnum


class Autopilot(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_AUTOPILOT entries starting with
    `MAV_AUTOPILOT_`.
    """

    AEROB = 16
    AIRRAILS = 19
    ARDUPILOTMEGA = 3
    ARMAZILA = 15
    ASLUAV = 17
    AUTOQUAD = 14
    ENUM_END = 21
    FP = 11
    GENERIC = 0
    GENERIC_MISSION_FULL = 7
    GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY = 6
    GENERIC_WAYPOINTS_ONLY = 5
    INVALID = 8
    OPENPILOT = 4
    PPZ = 9
    PX4 = 12
    REFLEX = 20
    RESERVED = 1
    SLUGS = 2
    SMACCMPILOT = 13
    SMARTAP = 18
    UDB = 10
