"""Autogenerated. ."""

from enum import IntEnum


class DataStream(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_DATA_STREAM entries starting with
    `MAV_DATA_STREAM_`.
    """

    ALL = 0
    ENUM_END = 13
    EXTENDED_STATUS = 2
    EXTRA1 = 10
    EXTRA2 = 11
    EXTRA3 = 12
    POSITION = 6
    RAW_CONTROLLER = 4
    RAW_SENSORS = 1
    RC_CHANNELS = 3
