"""Autogenerated. Bitflags indicating EKF estimator status."""

from enum import IntEnum


class EkfStatus(IntEnum):
    """
    Autogenerated. Autogenerated from EKF_STATUS_FLAGS entries starting with
    `EKF_`.
    """

    ATTITUDE = 1
    CONST_POS_MODE = 128
    GPS_GLITCHING = 32768
    POS_HORIZ_ABS = 16
    POS_HORIZ_REL = 8
    POS_VERT_ABS = 32
    POS_VERT_AGL = 64
    PRED_POS_HORIZ_ABS = 512
    PRED_POS_HORIZ_REL = 256
    STATUS_FLAGS_ENUM_END = 32769
    UNINITIALIZED = 1024
    VELOCITY_HORIZ = 2
    VELOCITY_VERT = 4

class EstimatorStatus(IntEnum):
  """
  PX4 uses `ESTIMATOR_` rather than `EKF_`.
  - https://mavlink.io/en/messages/common.html#ESTIMATOR_STATUS_FLAGS
  - https://docs.px4.io/main/en/msg_docs/EstimatorStatus
  """

  ESTIMATOR_ATTITUDE = 1
  ESTIMATOR_VELOCITY_HORIZ = 2
  ESTIMATOR_VELOCITY_VERT = 4
  ESTIMATOR_POS_HORIZ_REL = 8
  ESTIMATOR_POS_HORIZ_ABS = 16
  ESTIMATOR_POS_VERT_ABS = 32
	ESTIMATOR_POS_VERT_AGL = 64
  ESTIMATOR_CONST_POS_MODE = 128
  ESTIMATOR_PRED_POS_HORIZ_REL = 256
  ESTIMATOR_PRED_POS_HORIZ_ABS = 512
  ESTIMATOR_GPS_GLITCH = 1024
  ESTIMATOR_ACCEL_ERROR = 2048