"""Autogenerated. Coordinate frames for position and orientation."""

from enum import IntEnum


class Frame(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_FRAME entries starting with
    `MAV_FRAME_`.
    """

    BODY_FRD = 12
    BODY_NED = 8
    BODY_OFFSET_NED = 9
    ENUM_END = 22
    GLOBAL = 0
    GLOBAL_INT = 5
    GLOBAL_RELATIVE_ALT = 3
    GLOBAL_RELATIVE_ALT_INT = 6
    GLOBAL_TERRAIN_ALT = 10
    GLOBAL_TERRAIN_ALT_INT = 11
    LOCAL_ENU = 4
    LOCAL_FLU = 21
    LOCAL_FRD = 20
    LOCAL_NED = 1
    LOCAL_OFFSET_NED = 7
    MISSION = 2
    RESERVED_13 = 13
    RESERVED_14 = 14
    RESERVED_15 = 15
    RESERVED_16 = 16
    RESERVED_17 = 17
    RESERVED_18 = 18
    RESERVED_19 = 19
