""" MAVLink codes for PX4 flight mode. Serves same puprose as `coptermode.py` but for PX4.
    All enums are from the PX4-Autopilot source code: 
    github.com/PX4/PX4-Autopilot/blob/main/src/modules/commander/px4_custom_mode.h
"""
from enum import IntEnum

class CustomMainMode(IntEnum):
	PX4_CUSTOM_MAIN_MODE_MANUAL = 1
	PX4_CUSTOM_MAIN_MODE_ALTCTL = 2
	PX4_CUSTOM_MAIN_MODE_POSCTL = 3
	PX4_CUSTOM_MAIN_MODE_AUTO = 4
	PX4_CUSTOM_MAIN_MODE_ACRO = 5
	PX4_CUSTOM_MAIN_MODE_OFFBOARD = 6
	PX4_CUSTOM_MAIN_MODE_STABILIZED = 7
	PX4_CUSTOM_MAIN_MODE_RATTITUDE_LEGACY = 8
	PX4_CUSTOM_MAIN_MODE_SIMPLE = 9
	PX4_CUSTOM_MAIN_MODE_TERMINATION = 10
	PX4_CUSTOM_MAIN_MODE_ALTITUDE_CRUISE = 11

class CustomSubModeAuto(IntEnum):
	PX4_CUSTOM_SUB_MODE_AUTO_READY = 1
	PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF = 2
	PX4_CUSTOM_SUB_MODE_AUTO_LOITER = 3
	PX4_CUSTOM_SUB_MODE_AUTO_MISSION = 4
	PX4_CUSTOM_SUB_MODE_AUTO_RTL = 5
	PX4_CUSTOM_SUB_MODE_AUTO_LAND = 6
	PX4_CUSTOM_SUB_MODE_AUTO_RESERVED_DO_NOT_USE = 7
	PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET = 8
	PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND = 9
	PX4_CUSTOM_SUB_MODE_AUTO_VTOL_TAKEOFF = 10
	PX4_CUSTOM_SUB_MODE_EXTERNAL1 = 11
	PX4_CUSTOM_SUB_MODE_EXTERNAL2 = 12
	PX4_CUSTOM_SUB_MODE_EXTERNAL3 = 13
	PX4_CUSTOM_SUB_MODE_EXTERNAL4 = 14
	PX4_CUSTOM_SUB_MODE_EXTERNAL5 = 15
	PX4_CUSTOM_SUB_MODE_EXTERNAL6 = 16
	PX4_CUSTOM_SUB_MODE_EXTERNAL7 = 17
	PX4_CUSTOM_SUB_MODE_EXTERNAL8 = 18
	PX4_CUSTOM_SUB_MODE_GUIDED_COURSE = 19
	PX4_CUSTOM_SUB_MODE_AUTO_DESCEND = 20

class CustomSubModePOSCTL:
	PX4_CUSTOM_SUB_MODE_POSCTL_POSCTL = 0
	PX4_CUSTOM_SUB_MODE_POSCTL_ORBIT = 1
	PX4_CUSTOM_SUB_MODE_POSCTL_SLOW = 2