"""
Autogenerated. This selects the output PWM type, allowing for normal PWM
continuous output, OneShot, brushed or DShot motor output.PWMRange and PWMAngle
are PWM special/rare cases for ESCs that dont calibrate normally (some Sub
motors) or where each ESC must have its PWM range set individually using the
Servo params instead of PWM_MIN/MAX parameters.
"""

from enum import IntEnum


class MOTPWMType(IntEnum):
    """
    Autogenerated. This selects the output PWM type, allowing for normal PWM
    continuous output, OneShot, brushed or DShot motor output.PWMRange and
    PWMAngle are PWM special/rare cases for ESCs that dont calibrate
    normally (some Sub motors) or where each ESC must have its PWM range set
    individually using the Servo params instead of PWM_MIN/MAX parameters.
    Autogenerated from in file /home/abeldg/uav-cyber-
    sim/helpers/ardupilot/copter_params/apm.pdef.json.
    """

    Normal = 0
    OneShot = 1
    OneShot125 = 2
    Brushed = 3
    DShot150 = 4
    DShot300 = 5
    DShot600 = 6
    DShot1200 = 7
    PWMRange = 8
    PWMAngle = 9
