"""Autogenerated. Controls major frame class for multicopter component."""

from enum import IntEnum


class FrameClass(IntEnum):
    """
    Autogenerated. Controls major frame class for multicopter component
    Autogenerated from in file /home/abeldg/uav-cyber-
    sim/ardupilot/copter_params/apm.pdef.json.
    """

    Undefined = 0
    Quad = 1
    BiCopter = 10
    Heli_Dual = 11
    DodecaHexa = 12
    HeliQuad = 13
    Deca = 14
    Scripting_Matrix = 15
    _6DoF_Scripting = 16
    Dynamic_Scripting_Matrix = 17
    Hexa = 2
    Octa = 3
    OctaQuad = 4
    Y6 = 5
    Heli = 6
    Tri = 7
    SingleCopter = 8
    CoaxCopter = 9
