"""
Autogenerated. Controls motor mixing for multicopters.  Not used for Tri or
Traditional Helicopters.
"""

from enum import IntEnum


class FrameType(IntEnum):
    """
    Autogenerated. Controls motor mixing for multicopters.  Not used for Tri
    or Traditional Helicopters. Autogenerated from in file /home/abeldg/uav-
    cyber-sim/ardupilot/copter_params/apm.pdef.json.
    """

    Plus = 0
    X = 1
    Y6B = 10
    Y6F = 11
    BetaFlightX = 12
    DJIX = 13
    ClockwiseX = 14
    I = 15
    BetaFlightXReversed = 18
    Y4 = 19
    V = 2
    H = 3
    V_Tail = 4
    A_Tail = 5
