"""Mission Parameters."""

from enum import Enum


class WPNav(bytes, Enum):
    """
    Autogenerated from `WPNAV_` entries starting with `` in file
    /home/abeldg/uav-cyber-sim/ardupilot/copter_params/apm.pdef.json.
    """

    ACCEL = b"WPNAV_ACCEL"
    ACCEL_C = b"WPNAV_ACCEL_C"
    ACCEL_Z = b"WPNAV_ACCEL_Z"
    JERK = b"WPNAV_JERK"
    RADIUS = b"WPNAV_RADIUS"
    RFND_USE = b"WPNAV_RFND_USE"
    SPEED = b"WPNAV_SPEED"
    SPEED_DN = b"WPNAV_SPEED_DN"
    SPEED_UP = b"WPNAV_SPEED_UP"
    TER_MARGIN = b"WPNAV_TER_MARGIN"
