"""
Autogenerated. MAVLink commands used for setting parameters or system
configuration.
"""

from enum import IntEnum


class CmdSet(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_CMD entries starting with
    `MAV_CMD_SET_`.
    """

    CAMERA_FOCUS = 532
    CAMERA_MODE = 530
    CAMERA_SOURCE = 534
    CAMERA_ZOOM = 531
    EKF_SOURCE_SET = 42007
    FACTORY_TEST_MODE = 42427
    GUIDED_SUBMODE_CIRCLE = 4001
    GUIDED_SUBMODE_STANDARD = 4000
    HAGL = 43005
    MESSAGE_INTERVAL = 511
    STORAGE_USAGE = 533
