"""Autogenerated. MAVLink codes for Copter flight mode."""

from enum import IntEnum


class CopterMode(IntEnum):
    """
    Autogenerated. Autogenerated from COPTER_MODE entries starting with
    `COPTER_MODE_`.
    """

    ACRO = 1
    ALT_HOLD = 2
    AUTO = 3
    AUTOROTATE = 26
    AUTOTUNE = 15
    AUTO_RTL = 27
    AVOID_ADSB = 19
    BRAKE = 17
    CIRCLE = 7
    DRIFT = 11
    ENUM_END = 29
    FLIP = 14
    FLOWHOLD = 22
    FOLLOW = 23
    GUIDED = 4
    GUIDED_NOGPS = 20
    LAND = 9
    LOITER = 5
    POSHOLD = 16
    RTL = 6
    SMART_RTL = 21
    SPORT = 13
    STABILIZE = 0
    SYSTEMID = 25
    THROW = 18
    TURTLE = 28
    ZIGZAG = 24
