"""Autogenerated. MAVLink mission result codes."""

from enum import IntEnum


class MissionResult(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_MISSION_RESULT entries starting
    with `MAV_MISSION_`.
    """

    ACCEPTED = 0
    DENIED = 14
    ERROR = 1
    INVALID = 5
    INVALID_PARAM1 = 6
    INVALID_PARAM2 = 7
    INVALID_PARAM3 = 8
    INVALID_PARAM4 = 9
    INVALID_PARAM5_X = 10
    INVALID_PARAM6_Y = 11
    INVALID_PARAM7 = 12
    INVALID_SEQUENCE = 13
    NO_SPACE = 4
    OPERATION_CANCELLED = 15
    RESULT_ENUM_END = 16
    UNSUPPORTED = 3
    UNSUPPORTED_FRAME = 2
