"""Autogenerated. MAVLink codes used in PARAM_VALUE messages."""

from enum import IntEnum


class ParamType(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_PARAM_TYPE entries starting with
    `MAV_PARAM_TYPE_`.
    """

    ENUM_END = 11
    INT16 = 4
    INT32 = 6
    INT64 = 8
    INT8 = 2
    REAL32 = 9
    REAL64 = 10
    UINT16 = 3
    UINT32 = 5
    UINT64 = 7
    UINT8 = 1
