"""Autogenerated. MAVLink commands for conditions."""

from enum import IntEnum


class CmdCond(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_CMD entries starting with
    `MAV_CMD_CONDITION_`.
    """

    CHANGE_ALT = 113
    DELAY = 112
    DISTANCE = 114
    LAST = 159
    YAW = 115
