"""Autogenerated. MAVLink codes used to define the aircraft's landed status."""

from enum import IntEnum


class LandState(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_LANDED_STATE entries starting with
    `MAV_LANDED_STATE_`.
    """

    ENUM_END = 5
    IN_AIR = 2
    LANDING = 4
    ON_GROUND = 1
    TAKEOFF = 3
    UNDEFINED = 0
