"""
Autogenerated. Bitmask flags for UAV mode configuration (arming, control, etc).
"""

from enum import IntEnum


class ModeFlag(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_MODE_FLAG entries starting with
    `MAV_MODE_FLAG_`.
    """

    AUTO_ENABLED = 4
    CUSTOM_MODE_ENABLED = 1
    ENUM_END = 129
    GUIDED_ENABLED = 8
    HIL_ENABLED = 32
    MANUAL_INPUT_ENABLED = 64
    SAFETY_ARMED = 128
    STABILIZE_ENABLED = 16
    TEST_ENABLED = 2
