"""
Autogenerated. MAVLink data stream types. Used to control telemetry stream
rates.
"""

from enum import IntEnum


class Type(IntEnum):
    """
    Autogenerated. Autogenerated from MAV_TYPE entries starting with
    `MAV_TYPE_`.
    """

    ADSB = 27
    AIRSHIP = 7
    ANTENNA_TRACKER = 5
    BATTERY = 36
    CAMERA = 30
    CHARGING_STATION = 31
    COAXIAL = 3
    DECAROTOR = 35
    DODECAROTOR = 29
    ENUM_END = 43
    FIXED_WING = 1
    FLAPPING_WING = 16
    FLARM = 32
    FREE_BALLOON = 8
    GCS = 6
    GENERIC = 0
    GIMBAL = 26
    GPS = 41
    GROUND_ROVER = 10
    HELICOPTER = 4
    HEXAROTOR = 13
    IMU = 40
    KITE = 17
    LOG = 38
    OCTOROTOR = 14
    ODID = 34
    ONBOARD_CONTROLLER = 18
    OSD = 39
    PARACHUTE = 37
    PARAFOIL = 28
    QUADROTOR = 2
    ROCKET = 9
    SERVO = 33
    SUBMARINE = 12
    SURFACE_BOAT = 11
    TRICOPTER = 15
    VTOL_DUOROTOR = 19
    VTOL_QUADROTOR = 20
    VTOL_RESERVED2 = 22
    VTOL_RESERVED3 = 23
    VTOL_RESERVED4 = 24
    VTOL_RESERVED5 = 25
    VTOL_TILTROTOR = 21
    WINCH = 42
